apiVersion: apps/v1
kind: Deployment
metadata:
  name: cit270parkerservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cit270parkerservice
  template:
    metadata:
      - name: cit270parkerservice
      labels:
        app: cit270parkerservice
    spec:
      containers:
        - name: cit270parkerservice
        image: cit-270-kubernetes-379820/parker-api
        volumeMounts:
          - name: ssl
            mountPath: "/etc/letsencrypt/live/SSL"
        command: ["npm"]
        args: ["run", "start"]
        resources: 
          requests: 
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
        - name: ssl
        secret: 
          secretName: parkercerts